#pragma once

#define ASSET_PATH "assets\\"
#define WINDOW_WIDTH_LEFT 1200
#define WINDOW_HEIGHT_LEFT 600
#define CANVAS_WIDTH_LEFT 1000
#define CANVAS_HEIGHT_LEFT 500

#define WINDOW_WIDTH_RIGHT 1200
#define WINDOW_HEIGHT_RIGHT  600
#define CANVAS_WIDTH_RIGHT 1000
#define CANVAS_HEIGHT_RIGHT 500